### ISSUE TITLE
DocumentBuilder from the class WWXML throw error while running examples at start

### ISSUE THREAD

**Issue by crimmson** [NASAWorldWind/WorldWindJava#133]
### Description

Error in the thread main while launching any examples

Exception in thread "main" java.lang.AbstractMethodError: javax.xml.parsers.DocumentBuilderFactory.setFeature(Ljava/lang/String;Z)V
	at gov.nasa.worldwind.util.WWXML.createDocumentBuilder(WWXML.java:61)
	at gov.nasa.worldwind.util.WWXML.openDocumentStream(WWXML.java:236)
	at gov.nasa.worldwind.util.WWXML.openDocumentStream(WWXML.java:223)
	at gov.nasa.worldwind.util.WWXML.openDocumentFile(WWXML.java:175)
	at gov.nasa.worldwind.util.WWXML.openDocument(WWXML.java:148)
	at gov.nasa.worldwind.Configuration.loadConfigDoc(Configuration.java:131)
	at gov.nasa.worldwind.Configuration.<init>(Configuration.java:108)
	at gov.nasa.worldwind.Configuration.<clinit>(Configuration.java:76)
	at gov.nasa.worldwindx.examples.ApplicationTemplate.<clinit>(ApplicationTemplate.java:287)

### Steps to Reproduce

-Download last version of WorldWind and add the main directory in the default eclipse workspace
-Open Eclipse and create a new project with the WoldWindJava directory as Project Name. The project is recognized and the project is imported properly. The default option are used.
-Hit the "Run Cones" button

**Expected behavior:** [What you expect to happen]
To start the main Gui

**Actual behavior:** [What actually happens]
Java Virtual Machine Launcher Windows with error "A  Java Exception has occurred"

**Reproduces how often:** [What percentage of the time does it reproduce?]
All tries

### Operating System and Version

Windows 8.1

Java 8 Update 144 (build 1.8.0_144-b01)

Eclipse Java EE IDE for Web Developers.

Version: Oxygen Release (4.7.0)
Build id: 20170620-1800

### Additional Information

I checked the solution here 
https://forum.worldwindcentral.com/forum/world-wind-java-forums/development-help/15479-need-help-with-helloworldwind-java
Pointing to the other solution here:
https://stackoverflow.com/questions/18616079/example-worldwind-application-encounters-abstractmethoderror-when-started
The URL http://forum.worldwindcentral.com/showthread.php?t=20383 to "How to setup WWJ thread" doesn't exist anymore

Those are work around and not an actual fixes.

**Comment by DavideACucci** [comment]
The solution that crimmson pointed out [on stackoverflow](https://stackoverflow.com/questions/18616079/example-worldwind-application-encounters-abstractmethoderror-when-started) worked for me.
