### ISSUE TITLE
Gazetteer App does not retrieve locations

### ISSUE THREAD

**Issue by Beak-man** [NASAWorldWind/WorldWindJava#185]
### Description

When attempting to use the GazetteerApp example to retrieve a particular location, the following error appears:

![image](https://user-images.githubusercontent.com/7622894/67563093-db0be400-f6d4-11e9-824a-0dd61dcd76f0.png)

Error messages also appear in the console:

```
...
SEVERE: Exception while retrieving resources for https://worldwind25.arc.nasa.gov/wms?EXCEPTIONS=application/vnd.ogc.se_xml&REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.3.0
java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
...
````

### Steps to Reproduce

1. Run Gazetteer App example
2. Try to search for a location in the search box

**Expected behavior:**
App retrieves location and points the globe towards it.
**Actual behavior:**
Error message appears.
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Operating System and Version
Windows 10, Java 11 SDK.

**Comment by Beak-man** [comment]
The search box in the ` src/gov/nasa/worldwindx/examples/view/AddAnimator.java` example produces the same error.
