### ISSUE TITLE
Error reading from connection to https://data.worldwind.arc.nasa.gov/elev

### ISSUE THREAD

**Issue by Bio7** [NASAWorldWind/WorldWindJava#238]
### Description

I've embedded WorldWind in a Eclipse Rich Client Application. However the error I get seems to be a general SSL connection problem (server down?). 

Since a few days I get the following connection exception using the default layers:

gov.nasa.worldwind.retrieve.URLRetriever read
...: Error reading from connection to https://data.worldwind.arc.nasa.gov/elev?service=WMS&request=GetMap&version=1.3.0&crs=CRS:84&layers=mergedAsterElevations&styles=&format=application/bil16&width=150&height=150&bbox=-100.0,50.0,-80.0,70.0&
javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
	at java.base/sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:451)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:175)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at gov.nasa.worldwind.retrieve.HTTPRetriever.doRead(HTTPRetriever.java:48)
	at gov.nasa.worldwind.retrieve.URLRetriever.read(URLRetriever.java:368)
	at gov.nasa.worldwind.retrieve.URLRetriever.call(URLRetriever.java:244)
	at gov.nasa.worldwind.retrieve.URLRetriever.call(URLRetriever.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at gov.nasa.worldwind.retrieve.BasicRetrievalService$RetrievalTask.run(BasicRetrievalService.java:71)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

The application however runs fine.

### Steps to Reproduce

1. Start WorldWind with some default layers and the error will be thrown when a server for the maps is contacted. 

### Operating System and Version

Can be reproduced, e.g., on Mac.

**Comment by Bio7** [comment]
Is this error related to refreshed certificates as described here?

https://github.com/NASAWorldWind/WorldWindJava/issues/236

Is there a common way to fix this?
