### ISSUE TITLE
RigidShape Line intersection

### ISSUE THREAD

**Issue by fernandocarrillo** [NASAWorldWind/WorldWindJava#95]
I'm trying to create a cone and search for insertion points with a line

I get this error: 

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at gov.nasa.worldwind.render.RigidShape.intersect(RigidShape.java:1540)
	at gov.nasa.worldwind.render.RigidShape.intersect(RigidShape.java:1526)

	
Checking if "this.getCurrentShapeData()" is null solves the problem.

Actual Code:
if (this.getCurrentShapeData().getMesh(index).getBuffer(Geometry.VERTEX) == null)
           return null;

Bugfix Code:		   
if (this.getCurrentShapeData() !=null && this.getCurrentShapeData().getMesh(index).getBuffer(Geometry.VERTEX) == null)
           return null;

**Comment by basisbit** [comment]
this null check should not be necessary. Rather check why getCurrentShapeData returns null and fill that correctly.
